OBJS = prog.o queue.o
TARGET = test

CC = gcc
CFLAGS = -g -Wall 

.SUFFIXES: .c .o 

test: prog.o queue.o
	$(CC) $(CFLAGS) -o prog.o queue.o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

clean:
	-rm -f $(OBJS) test
